- name: feature
  color: 0e8a16
  description: "Novas funcionalidades"

- name: bug
  color: d73a4a
  description: "Correções de bug"

- name: maintenance
  color: fbca04
  description: "Atualizações de manutenção e refatoração"

- name: documentation
  color: 0075ca
  description: "Alterações na documentação"

- name: tests
  color: 5319e7
  description: "Mudanças relacionadas a testes"

- name: help wanted
  color: 008672
  description: "Projeto aceita ajuda nesta área"
